name: Liquibase Status with Spanner (Minimal)

on:
  workflow_dispatch:
    inputs:
      app_env:
        description: 'Environment (dev, stage, prod-c)'
        default: 'dev'
        required: true

env:
  CHANGE_LOG_FILE: sql/changelog-root.xml
  JDBC_URL: jdbc:cloudspanner:/projects/${{ vars.GCP_PROJECT_ID }}/instances/demo/databases/demo_liquibase?credentials=${{ github.workspace }}/sa-liquibase.json
  SEARCH_PATH: sql
  WORKSPACE: ${{ github.workspace }}

jobs:
  test-liquibase-status:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Maven Dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('pom.xml') }}-v1
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Resolve and Copy Dependencies (Minimal)
        run: |
          mkdir -p m2-repository
          mvn -B dependency:copy-dependencies \
            -DincludeArtifactIds=google-cloud-spanner-jdbc,google-cloud-spanner,guava,protobuf-java \
            -Dmdep.outputDirectory=m2-repository
        working-directory: ${{ env.WORKSPACE }}

      - name: Save Service Account Key
        run: echo "${{ secrets.GCP_SA_KEY }}" > ${{ env.WORKSPACE }}/sa-liquibase.json

      - name: Check for Changelog File
        id: check_sql
        run: |
          if [ -f "${{ env.WORKSPACE }}/${{ env.CHANGE_LOG_FILE }}" ]; then
            echo "root_xml=true" >> $GITHUB_OUTPUT
          else
            echo "root_xml=false" >> $GITHUB_OUTPUT
          fi

      - name: Run Liquibase Status
        id: liquibase_status
        if: steps.check_sql.outputs.root_xml == 'true'
        uses: liquibase-github-actions/status@v4.31.1
        with:
          changelogFile: ${{ env.CHANGE_LOG_FILE }}
          url: ${{ env.JDBC_URL }}
          driver: com.google.cloud.spanner.jdbc.JdbcDriver
          searchPath: ${{ env.SEARCH_PATH }}
          classpath: |
            ${{ env.WORKSPACE }}/m2-repository/com/google/cloud/google-cloud-spanner-jdbc/2.14.1/google-cloud-spanner-jdbc-2.14.1.jar:
            ${{ env.WORKSPACE }}/m2-repository/com/google/cloud/google-cloud-spanner/6.67.0/google-cloud-spanner-6.67.0.jar:
            ${{ env.WORKSPACE }}/m2-repository/com/google/guava/guava/33.3.0-jre/guava-33.3.0-jre.jar:
            ${{ env.WORKSPACE }}/m2-repository/com/google/protobuf/protobuf-java/3.25.5/protobuf-java-3.25.5.jar
          contextFilter: ${{ inputs.app_env }}
          logLevel: debug
        env:
          JAVA_HOME: /opt/java/openjdk
          GOOGLE_APPLICATION_CREDENTIALS: ${{ env.WORKSPACE }}/sa-liquibase.json

      - name: Output Results
        if: steps.check_sql.outputs.root_xml == 'true'
        run: |
          echo "Changesets:"
          echo "${{ steps.liquibase_status.outputs.changesets }}"
