name: Liquibase Spanner Status and Update

on:
  workflow_dispatch:
    inputs:
      app_env:
        description: 'Environment (e.g., dev)'
        default: 'dev'
        required: true
      spanner_instance:
        description: 'Spanner instance (e.g., demo)'
        default: 'demo'
        required: true
      app_version:
        description: 'Version tag (e.g., v1.0.0)'
        default: 'v1.0.0'
        required: true

env:
  CHANGE_LOG_FILE: sql/changelog-root.xml
  LIQUIBASE_IMAGE: liquibase:4.29.0
  SEARCH_PATH: /liquibase/workspace,/liquibase/workspace/sql
  LIQUIBASE_CONFIG: liquibase.properties

jobs:
  liquibase-spanner:
    runs-on: ubuntu-22.04
    timeout-minutes: 15
    permissions:
      contents: read
    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Variables
        run: |
          echo "JDBC_URL=jdbc:cloudspanner:/projects/${{ vars.GCP_PROJECT_ID }}/instances/${{ inputs.spanner_instance }}/databases/demo_liquibase_spanner" >> "$GITHUB_ENV"
          echo "APP_ENV=${{ inputs.app_env }}" >> "$GITHUB_ENV"
          echo "APP_VERSION=${{ inputs.app_version }}" >> "$GITHUB_ENV"

      - name: GCP Authentication
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'
          create_credentials_file: true

      - name: Copy Credentials
        run: cp "$GOOGLE_APPLICATION_CREDENTIALS" "${{ github.workspace }}/gcp-creds.json"

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install Maven
        run: sudo apt-get update && sudo apt-get install -y maven

      - name: Create POM for Dependencies
        run: |
          cat <<EOF > pom.xml
          <?xml version="1.0" encoding="UTF-8"?>
          <project xmlns="http://maven.apache.org/POM/4.0.0"
                   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                   xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
              <modelVersion>4.0.0</modelVersion>
              <groupId>com.example</groupId>
              <artifactId>liquibase-spanner</artifactId>
              <version>1.0-SNAPSHOT</version>
              <dependencies>
                  <dependency>
                      <groupId>com.google.cloud</groupId>
                      <artifactId>google-cloud-spanner-jdbc</artifactId>
                      <version>2.30.1</version>
                  </dependency>
                  <dependency>
                      <groupId>com.google.cloudspannerecosystem</groupId>
                      <artifactId>liquibase-spanner</artifactId>
                      <version>4.20.0</version>
                  </dependency>
                  <dependency>
                      <groupId>com.google.cloud</groupId>
                      <artifactId>google-cloud-spanner</artifactId>
                      <version>6.81.0</version>
                  </dependency>
              </dependencies>
          </project>
          EOF

      - name: Download Dependencies
        run: |
          mkdir -p liquibase-lib
          mvn dependency:copy-dependencies -DoutputDirectory=liquibase-lib

      - name: Configure Liquibase Properties
        run: |
          docker run --rm \
            -v "${{ github.workspace }}:/liquibase/workspace" \
            --entrypoint=/bin/sh \
            ${{ env.LIQUIBASE_IMAGE }} \
            -c "CLASSPATH='/liquibase/internal/lib/liquibase-core.jar'; \
                for jar in /liquibase/workspace/liquibase-lib/*.jar; do \
                  [ -f \"\$jar\" ] && CLASSPATH=\"\$CLASSPATH:\$jar\"; \
                done; \
                echo \"classpath=\$CLASSPATH\" > /liquibase/workspace/${{ env.LIQUIBASE_CONFIG }}; \
                echo 'driver=com.google.cloud.spanner.jdbc.JdbcDriver' >> /liquibase/workspace/${{ env.LIQUIBASE_CONFIG }}; \
                echo 'url=${{ env.JDBC_URL }}?credentials=/liquibase/workspace/gcp-creds.json;lenient=true' >> /liquibase/workspace/${{ env.LIQUIBASE_CONFIG }}; \
                echo 'changeLogFile=${{ env.CHANGE_LOG_FILE }}' >> /liquibase/workspace/${{ env.LIQUIBASE_CONFIG }}; \
                echo 'searchPath=${{ env.SEARCH_PATH }}' >> /liquibase/workspace/${{ env.LIQUIBASE_CONFIG }}"

      - name: Check Liquibase Status
        id: liquibase-status
        if: env.APP_ENV == 'dev'
        run: |
          docker run --rm \
            -v "${{ github.workspace }}:/liquibase/workspace" \
            -e GOOGLE_APPLICATION_CREDENTIALS=/liquibase/workspace/gcp-creds.json \
            ${{ env.LIQUIBASE_IMAGE }} \
            status --defaultsFile=/liquibase/workspace/${{ env.LIQUIBASE_CONFIG }} --contexts=${{ env.APP_ENV }}

      - name: Run Liquibase Update
        if: env.APP_ENV == 'dev'
        run: |
          docker run --rm \
            -v "${{ github.workspace }}:/liquibase/workspace" \
            -e GOOGLE_APPLICATION_CREDENTIALS=/liquibase/workspace/gcp-creds.json \
            ${{ env.LIQUIBASE_IMAGE }} \
            update --defaultsFile=/liquibase/workspace/${{ env.LIQUIBASE_CONFIG }} --contexts=${{ env.APP_ENV }}