name: Liquibase Docker with Spanner

on:
  workflow_dispatch:
    inputs:
      app_env:
        description: 'Environment (dev, stage, prod-c)'
        default: 'dev'
        required: true
      spanner_instance:
        description: 'Spanner instance (e.g., demo)'
        default: 'demo'
        required: true

env:
  CHANGE_LOG_FILE: sql/changelog-root.xml
  JDBC_URL: jdbc:cloudspanner:/projects/${{ vars.GCP_PROJECT_ID }}/instances/${{ inputs.spanner_instance }}/databases/demo_liquibase
  SEARCH_PATH: ${{ github.workspace }},${{ github.workspace }}/sql

jobs:
  liquibase-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: GCP Authentication
        id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'
          export_environment_variables: true
          create_credentials_file: true

      - name: Copy Credentials to Workspace
        run: cp "$GOOGLE_APPLICATION_CREDENTIALS" "${{ github.workspace }}/gcp-creds.json"
        shell: bash

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install Maven
        run: sudo apt-get update && sudo apt-get install -y maven

      - name: Download Liquibase Spanner Extension
        run: |
          mkdir -p "${{ github.workspace }}/liquibase-lib"
          mvn dependency:copy -Dartifact=com.google.cloudspannerecosystem:liquibase-spanner:4.20.0:jar \
            -DoutputDirectory="${{ github.workspace }}/liquibase-lib"
          ls -l "${{ github.workspace }}/liquibase-lib"
          if [ -f "${{ github.workspace }}/liquibase-lib/liquibase-spanner-4.20.0.jar" ]; then
            echo "Liquibase Spanner extension found"
          else
            echo "ERROR: Liquibase Spanner extension not found"
            exit 1
          fi
        shell: bash

      - name: Download Spanner JDBC Driver
        run: |
          mvn dependency:copy -Dartifact=com.google.cloud:google-cloud-spanner-jdbc:2.30.1:jar \
            -DoutputDirectory="${{ github.workspace }}/liquibase-lib"
          ls -l "${{ github.workspace }}/liquibase-lib"
          if [ -f "${{ github.workspace }}/liquibase-lib/google-cloud-spanner-jdbc-2.30.1.jar" ]; then
            echo "Spanner JDBC driver found"
            unzip -l "${{ github.workspace }}/liquibase-lib/google-cloud-spanner-jdbc-2.30.1.jar" | grep com/google/cloud/spanner/jdbc/JdbcDriver || echo "ERROR: Driver not found in JAR"
          else
            echo "ERROR: Spanner JDBC driver not found"
            exit 1
          fi
        shell: bash

      - name: Configure Liquibase Properties
        run: |
          echo "liquibase.defaultSchemaName=" > "${{ github.workspace }}/liquibase.properties"
          echo "liquibase.classpath=${{ github.workspace }}/liquibase-lib/liquibase-spanner-4.20.0.jar:${{ github.workspace }}/liquibase-lib/google-cloud-spanner-jdbc-2.30.1.jar" >> "${{ github.workspace }}/liquibase.properties"
          cat "${{ github.workspace }}/liquibase.properties"
        shell: bash

      - name: Run Liquibase Update
        run: |
          docker run --rm \
            -v "${{ github.workspace }}:/liquibase" \
            -e GOOGLE_APPLICATION_CREDENTIALS=/liquibase/gcp-creds.json \
            liquibase/liquibase:4.32.0 \
            --defaultsFile=/liquibase/liquibase.properties \
            --url="${{ env.JDBC_URL }}" \
            --driver=com.google.cloud.spanner.jdbc.JdbcDriver \
            --changelog-file="${{ env.CHANGE_LOG_FILE }}" \
            --search-path="${{ env.SEARCH_PATH }}" \
            --context-filter="${{ inputs.app_env }}" \
            --log-level=debug \
            update
        shell: bash

      - name: Run Liquibase Status
        run: |
          docker run --rm \
            -v "${{ github.workspace }}:/liquibase" \
            -e GOOGLE_APPLICATION_CREDENTIALS=/liquibase/gcp-creds.json \
            liquibase/liquibase:4.32.0 \
            --defaultsFile=/liquibase/liquibase.properties \
            --url="${{ env.JDBC_URL }}" \
            --driver=com.google.cloud.spanner.jdbc.JdbcDriver \
            --changelog-file="${{ env.CHANGE_LOG_FILE }}" \
            --search-path="${{ env.SEARCH_PATH }}" \
            --context-filter="${{ inputs.app_env }}" \
            --log-level=debug \
            status --verbose
        shell: bash

      - name: Output Results
        if: always()
        run: ls -l "${{ github.workspace }}"
        shell: bash