name: Liquibase Status with Spanner

on:
  workflow_dispatch:
    inputs:
      app_env:
        description: 'Environment (dev, stage, prod-c)'
        default: 'dev'
        required: true
      spanner_instance:
        description: 'Spanner instance (e.g., demo)'
        default: 'demo'
        required: true

env:
  CHANGE_LOG_FILE: sql/changelog-root.xml
  JDBC_URL: jdbc:cloudspanner:/projects/${{ vars.GCP_PROJECT_ID }}/instances/${{ inputs.spanner_instance }}/databases/demo_liquibase?credentials=/github/workspace/lib/sa-credential
  SEARCH_PATH: sql
  WORKSPACE: ${{ github.workspace }}

jobs:
  test-liquibase-status:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: GCP Authentication
        uses: google-github-actions/auth@v2
        with: 
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install Maven
        run: |
          sudo apt-get update
          sudo apt-get install -y maven

      - name: Verify JAVA_HOME
        run: |
          echo "JAVA_HOME is set to: $JAVA_HOME"
          ls -l "$JAVA_HOME"
          # Resolve the symlink to get the actual path
          RESOLVED_JAVA_HOME=$(readlink -f "$JAVA_HOME")
          echo "Resolved JAVA_HOME: $RESOLVED_JAVA_HOME"
        shell: bash

      - name: Download JDBC driver
        run: |
          mkdir -p "${{ env.WORKSPACE }}/lib"
          cd "${{ env.WORKSPACE }}/lib"
          # Clean up unexpected files
          rm -f spanner-jdbc-driver.jar
          cat <<EOF > pom.xml
          <project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                   xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
            <modelVersion>4.0.0</modelVersion>
            <groupId>com.example</groupId>
            <artifactId>temp</artifactId>
            <version>1.0-SNAPSHOT</version>
            <dependencies>
              <dependency>
                <groupId>com.google.cloud</groupId>
                <artifactId>google-cloud-spanner-jdbc</artifactId>
                <version>2.30.1</version>
              </dependency>
            </dependencies>
            <repositories>
              <repository>
                <id>central</id>
                <url>https://repo.maven.apache.org/maven2</url>
              </repository>
            </repositories>
          </project>
          EOF
          echo "<settings></settings>" > /tmp/settings.xml
          mvn dependency:copy-dependencies -s /tmp/settings.xml
          ls -l "${{ env.WORKSPACE }}/lib"
          ls -l "${{ env.WORKSPACE }}/lib/target/dependency"
          if [ -f "${{ env.WORKSPACE }}/lib/target/dependency/google-cloud-spanner-jdbc-2.30.1.jar" ]; then
            echo "Spanner JDBC driver found"
            unzip -l "${{ env.WORKSPACE }}/lib/target/dependency/google-cloud-spanner-jdbc-2.30.1.jar" | grep com/google/cloud/spanner/jdbc/JdbcDriver || echo "ERROR: Driver class not found in JAR"
          else
            echo "ERROR: Spanner JDBC driver not found"
            exit 1
          fi
        shell: bash

      - name: Save Service Account Key
        run: echo "${{ secrets.GCP_SA_KEY }}" > "${{ env.WORKSPACE }}/lib/sa-credential"
        shell: bash

      - name: Verify Service Account
        run: |
          ls -l "${{ env.WORKSPACE }}/lib/sa-credential"
          cat "${{ env.WORKSPACE }}/lib/sa-credential" | head -n 2
        shell: bash

      - name: Debug Classpath
        run: |
          echo "Listing contents of ${{ github.workspace }}/lib in host:"
          ls -l "${{ github.workspace }}/lib"
          echo "Listing contents of ${{ github.workspace }}/lib/target/dependency in host:"
          ls -l "${{ github.workspace }}/lib/target/dependency"
          # Run a command in the Liquibase Docker image to check classpath
          docker run --rm \
            -v "${{ github.workspace }}:/github/workspace" \
            liquibase/liquibase:4.30.0 \
            bash -c "echo 'Listing contents of /github/workspace/lib in container:' && ls -l /github/workspace/lib; echo 'Listing contents of /github/workspace/lib/target/dependency in container:' && ls -l /github/workspace/lib/target/dependency; echo 'Working directory:' && pwd"
        shell: bash

      - name: Run Liquibase Status
        id: liquibase_status
        uses: liquibase-github-actions/status@v4.30.0
        with:
          changelogFile: ${{ env.CHANGE_LOG_FILE }}
          url: "${{ env.JDBC_URL }}"
          driver: com.google.cloud.spanner.jdbc.JdbcDriver
          searchPath: "${{ env.SEARCH_PATH }}"
          classpath: lib/target/dependency
          contextFilter: ${{ inputs.app_env }}
          logLevel: debug
        env:
          JAVA_HOME: ""

      - name: Output Results
        if: always()
        run: |
          echo "Changesets:"
          echo "${{ steps.liquibase_status.outputs.output }}"
          if [ -f liquibase.log ]; then
            echo "Liquibase Log:"
            cat liquibase.log
          fi
        shell: bash